project:
  type: website
  output-dir: _site

website:
  title: "CUMBIAH DETF"
  favicon: images/cumbiah-icon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    toc: false
